### ISSUE TITLE
请问怎么在Python代码中播放？

### ISSUE THREAD

**Issue by SilenceWinter** [kuangdd/ttskit#38]
from ttskit import sdk_api

wav = sdk_api.tts_sdk('文本', audio='24')
怎么让他放出声音

**Comment by SilenceWinter** [comment]
已解决

**Comment by kuangdd** [comment]
保存下来，本地播放。

或者用aukit的工具播放

import aukit

aukit.play_audio(wav, sr=16000)



在 2023-01-31 21:00:09，"SilenceWinter" ***@***.***> 写道：

from ttskit import sdk_api

wav = sdk_api.tts_sdk('文本', audio='24')
怎么让他放出声音
